version: '3.4'

networks:
    backend:

services:

  superdb:
    container_name: "super-db"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
    networks:
      - backend
    ports:
      - 18001:1433

  movieservice:
    container_name: movie-service
    image: ${DOCKER_REGISTRY-}movieservice
    build:
      context: .
      dockerfile: MovieService/Dockerfile
    depends_on:
      - superdb
    environment:
      - DB_HOST=superdb
      - DB_NAME=moviedb
      - DB_SA_PASSWORD=Password@123
    networks:
      - backend

  userservice:
    container_name: user-service
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    depends_on:
      - superdb
    environment:
      - DB_HOST=superdb
      - DB_NAME=userdb
      - DB_SA_PASSWORD=Password@123
    networks:
      - backend

  apigateway:
    container_name: "api-gateway"
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - backend
    ports:
      - 18000:80
      - 25000:443

  authenticationservice:
    container_name: "authentication-service"
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    networks:
      backend: